(function(g){var window=this;var Uta=function(a,b){var c=[];g.Nf(b,function(a){var b;try{b=g.hj.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.p(b)?g.gj(b)&&c.push(a):c.push(a)},a);
return c},Vta=function(a,b){var c=Uta(a,b);
(0,g.H)(c,function(a){g.hj.prototype.remove.call(this,a)},a)},Wta=function(a){return a.H?a.F+((0,g.G)()-a.A)/1E3:a.F},Xta=function(){var a=g.ij;
Vta(a,a.g.Fd(!0))},u9=function(a){g.Hw.call(this,"ScreenServiceProxy");
this.Sc=a;this.o=[];this.o.push(this.Sc.$_s("screenChange",(0,g.z)(this.JN,this)));this.o.push(this.Sc.$_s("onlineScreenChange",(0,g.z)(this.lK,this)))},v9=function(a){g.Dw("cloudview",a)},Yta=function(a){v9("setApiReady_ "+a);
g.oa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},w9=function(){return g.u("yt.mdx.remote.cloudview.instance_")},Zta=function(a){g.Mi[a]&&(a=g.Mi[a],(0,g.H)(a,function(a){g.Ki[a]&&delete g.Ki[a]}),a.length=0)},x9=function(){return g.u("yt.mdx.remote.connection_")},y9=function(a){g.oa("yt.mdx.remote.connectData_",a,void 0)},$ta=function(a){g.oa("yt.mdx.remote.currentScreenId_",a,void 0)},z9=function(){return g.u("yt.mdx.remote.currentScreenId_")},B9=function(){if(!A9){var a=g.u("yt.mdx.remote.screenService_");
A9=a?new u9(a):null}return A9},C9=function(a){g.oa("yt.mdx.remote.cloudview.initializing_",a,void 0)},D9=function(){return!!g.u("yt.mdx.remote.cloudview.apiReady_")},E9=function(a){v9("setCastInstalled_ "+a);
g.kj("yt-remote-cast-installed",a)},F9=function(a){g.Dw("cloudview",a)},aua=function(a,b){w9().init(a,b)},G9=function(){return!!g.lj("yt-remote-cast-installed")},bua=function(){v9("dispose");
var a=w9();a&&a.dispose();g.oa("yt.mdx.remote.cloudview.instance_",null,void 0);Yta(!1);g.Oi(H9);H9.length=0},cua=function(){var a=window.document.createElement("a");
g.ze(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Ta(a)},dua=function(a,b){var c=window.document.createElement("script");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
c.src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js";var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},eua=function(a){var b=g.Ii();
if(b)if(b.clear(a),a)Zta(a);else for(var c in g.Mi)Zta(c)},I9=function(){return g.u("yt.mdx.remote.channelParams_")||{}},K9=function(a){var b=x9();
y9(null);a||$ta("");g.oa("yt.mdx.remote.connection_",a,void 0);J9&&((0,g.H)(J9,function(b){b(a)}),J9.length=0);
b&&!a?g.Ri("yt-remote-connection-change",!1):!b&&a&&g.Ri("yt-remote-connection-change",!0)},fua=function(){return g.u("yt.mdx.remote.connectData_")},L9=function(){var a=z9();
if(!a)return null;var b=B9().Kd();return g.mi(b,a)},gua=function(a,b){E9(!0);
C9(!1);aua(a,function(a){a?(Yta(!0),g.Qi("yt-remote-cast2-api-ready")):(F9("Failed to initialize cast API."),E9(!1),g.mj("yt-remote-cast-available"),g.mj("yt-remote-cast-receiver"),bua());b(a)})},hua=function(){return G9()?w9()?w9().getCastSession():(F9("getCastSelector: Cast is not initialized."),null):(F9("getCastSelector: Cast API is not installed!"),null)},iua=function(){if(g.uoa){var a=2,b=g.rw(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;g.xw("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",g.uw,c)}},jua=function(){var a=cua(),b=window.document.getElementById(a),c=b&&g.hh(b,"loaded");
c||b&&!c||(b=dua(a,function(){g.hh(b,"loaded")||(g.ih(b,"loaded","true"),g.Qi(a),g.ui(g.A(eua,a),0))}))},kua=function(a){return(0,g.R)(a,function(a){return{key:a.id,
name:a.name}})},N9=function(a,b){z9();
L9()&&L9();$ta(a.id);var c=new g.Ty(M9,a,I9());c.connect(b,fua());c.subscribe("beforeDisconnect",function(a){g.Ri("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){x9()&&(x9(),K9(null))});
K9(c)},O9=function(){var a=g.pj();
if(!a)return null;var b=B9().Kd();return g.mi(b,a)},P9=function(a){g.Dw("remote",a)},Q9=function(){var a=x9();
return!!a&&3!=a.getProxyState()},R9=function(){D9()?w9().stopSession():F9("stopSession called before API ready.");
var a=x9();a&&(a.disconnect(1),K9(null))},lua=function(){var a;
a=B9().Sc.$_gos();var b=L9();b&&x9()&&(g.li(a,b)||a.push(b));return kua(a)},T9=function(a,b){g.bl.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.Iy;this.A=this.o=null;this.H=(0,g.z)(this.yI,this);this.F=(0,g.z)(this.Uj,this);this.G=(0,g.z)(this.xI,this);this.J=(0,g.z)(this.II,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.vr,this),mua(this))):c=3;0!=c&&(b?this.vr(c):g.ui((0,g.z)(function(){this.vr(c)},this),0));
var d=hua();d&&S9(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},U9=function(a){return new g.Ny(a.B.getPlayerContextData())},nua=function(a,b,c,d,e){var f=U9(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.Ry(f,b,d);g.p(c)&&(g.Py(f,c),l.currentTime=c);g.p(k)&&(l.listId=k);V9(a,"setPlaylist",l);e||W9(a,f)},mua=function(a){(0,g.H)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.A(this.FK,a),this))},a)},oua=function(a){(0,g.H)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},X9=function(a,b){50>a.C.Cc()&&g.Ky(a.C,b)},Y9=function(a,b,c){var d=U9(a);
g.Py(d,c);-1E3!=d.g&&(d.g=b);W9(a,d)},V9=function(a,b,c){a.B.sendMessage(b,c)},W9=function(a,b){oua(a);
a.B.setPlayerContextData(g.Sy(b));mua(a)},S9=function(a,b){a.A&&(a.A.removeUpdateListener(a.H),a.A.removeMediaListener(a.F),a.Uj(null));
a.A=b;a.A&&(Z9("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.H),a.A.addMediaListener(a.F),a.A.media.length&&a.Uj(a.A.media[0]))},pua=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=U9(a);b.contentId!=d.videoId&&Z9("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.Py(d,a.o.getEstimatedTime());W9(a,d)}else Z9("No cast media video. Ignoring state update.")},Z9=function(a){g.Dw("CP",a)},$9=function(a,b,c){return(0,g.z)(function(a){this.Xb("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.Xb("Retrying "+b+" using MDx browser channel."),V9(this,b,c))},a)},qua=function(a){var b=!1;
w9()||(a=new g.hx(a),a.subscribe("yt-remote-cast2-availability-change",function(a){g.kj("yt-remote-cast-available",a);g.Ri("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){v9("onReceiverSelected: "+a.friendlyName);
g.kj("yt-remote-cast-receiver",a);g.Ri("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){v9("onReceiverResumed: "+a.friendlyName);
g.kj("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){v9("onSessionChange: "+g.ii(a));
a||g.mj("yt-remote-cast-receiver");g.Ri("yt-remote-cast2-session-change",a)}),g.oa("yt.mdx.remote.cloudview.instance_",a,void 0),b=!0);
v9("cloudview.createSingleton_: "+b);return b},rua=function(){var a=0<=g.hc.search(/\ (CrMo|Chrome|CriOS)\//);
return g.Ei||a},a$=function(a,b){D9()?w9().setConnectedScreenStatus(a,b):F9("setConnectedScreenStatus called before ready.")},sua=function(){v9("clearCurrentReceiver");
g.mj("yt-remote-cast-receiver")},tua=function(){if(0<=window.navigator.userAgent.indexOf("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){iua();a({command:"cast.sender.init"});return}}if(window.chrome)if(iua(),a=window.navigator.userAgent,0<=a.indexOf("Android")&&0<=a.indexOf("Chrome/")&&window.navigator.presentation){var a="",b=g.pw();55<=b?a="55":50<=b&&(a="50");g.xw("//www.gstatic.com/eureka/clank"+a+g.vw,g.uw)}else g.yw(0);else g.uw()},uua=function(a){a?(g.kj("yt-remote-session-app",a.app),g.kj("yt-remote-session-name",a.name)):(g.mj("yt-remote-session-app"),g.mj("yt-remote-session-name"));
g.oa("yt.mdx.remote.channelParams_",a,void 0)},vua=function(){var a=I9();
if(g.Ub(a)){var a=g.oj(),b=g.lj("yt-remote-session-name")||"",c=g.lj("yt-remote-session-app")||"",a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.oa("yt.mdx.remote.channelParams_",a,void 0)}},wua=function(){var a=O9();
a?(P9("Resume connection to: "+g.ii(a)),N9(a,0)):(g.yj(),sua(),P9("Skipping connecting because no session screen found."))},xua=function(a){P9("remote.onCastSessionChange_: "+g.ii(a));
if(a){var b=L9();b&&b.id==a.id?a$(b.id,"YouTube TV"):(b&&R9(),N9(a,1))}else x9()&&R9()},yua=function(){var a=lua(),b=L9();
b||(b=O9());return g.ab(a,function(a){return b&&g.fi(b,a.key)?!0:!1})},zua=function(){var a=g.lj("yt-remote-cast-receiver");
return a?a.friendlyName:null},Aua=function(a,b,c,d){rua()?qua(b)&&(C9(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?gua(a,c):(window.__onGCastApiAvailable=function(b,d){b?gua(a,c):(F9("Failed to load cast API: "+d),E9(!1),C9(!1),g.mj("yt-remote-cast-available"),g.mj("yt-remote-cast-receiver"),bua(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):jua():tua())):v9("Cannot initialize because not running Chrome")},
Bua=function(a){this.B=this.A="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.Zf(a)||"";b&&(this.B=":"+b);this.A=g.Yf(a)||"";a=g.hc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Sa(a,"10.0")&&(this.o=!1))},b$=function(a,b,c){g.J.call(this);
this.H=a;this.aa=b;b.addEventListener("onVolumeChange",this.Cm,this);b.addEventListener("onCaptionsTrackListChanged",this.Tw,this);b.addEventListener("captionschanged",this.Hw,this);b.addEventListener("captionssettingschanged",this.Oq,this);b.addEventListener("videoplayerreset",this.Xj,this);b.addEventListener("mdxautoplaycancel",this.xt,this);this.C=!1;this.g=c;c.isDisposed();c.subscribe("proxyStateChange",this.ix,this);c.subscribe("remotePlayerChange",this.Wj,this);c.subscribe("remoteQueueChange",
this.Xj,this);c.subscribe("autoplayUpNext",this.Fw,this);c.subscribe("previousNextChange",this.fx,this);c.subscribe("nowAutoplaying",this.Ww,this);c.subscribe("autoplayDismissed",this.Ew,this);this.suggestion=null;this.D=new g.Ol(64);this.o=new g.Nd(this.Ey,500,this);g.L(this,this.o);this.A=new g.Nd(this.Fy,1E3,this);g.L(this,this.A);this.B={};this.G=new g.Nd(this.Vy,1E3,this);g.L(this,this.G);this.F=new g.jw(this.IP,1E3,this);g.L(this,this.F);this.J=g.w;this.Oq();this.Xj();this.Wj()},c$=function(a,
b){var c=a.H,d=a.aa.getVideoData().lengthSeconds;
c.H=b||0;c.g.V("progresssync",b,d)},Cua=function(a){c$(a,0);
a.o.stop();d$(a,new g.Ol(64))},g$=function(a,b){if(e$(a)&&!a.C){var c=null;
b&&(c={style:a.aa.Ck()},g.ac(c,b));a.g.wy(f$(a),c);a.B=U9(a.g).o}},h$=function(a,b){var c=a.aa.Le();
c?nua(a.g,f$(a),b,c.Id(),c.listId.toString()):nua(a.g,f$(a),b);d$(a,new g.Ol(1))},Dua=function(a,b){if(b){var c=a.aa.Uc("captions","tracklist",{Iv:1});
c&&c.length?(a.aa.oe("captions","track",b),a.C=!1):(a.aa.yk("captions"),a.C=!0)}else a.aa.oe("captions","track",{})},e$=function(a){return U9(a.g).videoId==f$(a)},f$=function(a){return a.aa.getVideoData().videoId},d$=function(a,b){a.A.stop();
var c=a.D;if(b.o!=c.o||b.g!=c.g){var d=g.T(b,2);if(d!=g.T(a.D,2)){var e=a.aa;(e=g.om(e.app,e.playerType||1))&&g.NU(e,d)}a.D=b;Eua(a.H,c,b)}},i$=function(){var a=yua();
!a&&G9()&&zua()&&(a={key:"cast-selector-receiver",name:zua()});return a},Fua=function(){var a=lua();
G9()&&g.lj("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Gua=function(a){var b={device:"Desktop",
app:"youtube-desktop"};g.ij&&Xta();g.rj();M9||(M9=new Bua,g.Aj()&&(M9.g="/api/loungedev"));J9||(J9=g.u("yt.mdx.remote.deferredProxies_")||[],g.oa("yt.mdx.remote.deferredProxies_",J9,void 0));vua();var c=B9();if(!c){var d=new g.Uw(M9);g.oa("yt.mdx.remote.screenService_",d,void 0);c=B9();Aua(a,d,function(a){a?z9()&&a$(z9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){g.Ri("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript))}b&&!g.u("yt.mdx.remote.initialized_")&&
(g.oa("yt.mdx.remote.initialized_",!0,void 0),P9("Initializing: "+g.xf(b)),j$.push(g.Ni("yt-remote-cast2-availability-change",function(){g.Ri("yt-remote-receiver-availability-change")})),j$.push(g.Ni("yt-remote-cast2-receiver-selected",function(){y9(null);
g.Ri("yt-remote-auto-connect","cast-selector-receiver")})),j$.push(g.Ni("yt-remote-cast2-receiver-resumed",function(){g.Ri("yt-remote-receiver-resumed","cast-selector-receiver")})),j$.push(g.Ni("yt-remote-cast2-session-change",xua)),j$.push(g.Ni("yt-remote-connection-change",function(a){a?a$(z9(),"YouTube TV"):O9()||(a$(null,null),sua())})),a=I9(),b.isAuto&&(a.id+="#dial"),g.Fh("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,P9(" -- with channel params: "+g.xf(a)),
uua(a),c.start(),z9()||wua())},k$=function(){G9()?w9()?D9()?(v9("Requesting cast selector."),w9().requestSession()):(v9("Wait for cast API to be ready to request the session."),H9.push(g.Ni("yt-remote-cast2-api-ready",k$))):F9("requestCastSelector: Cast is not initialized."):F9("requestCastSelector: Cast API is not installed!")},l$=function(a){g.ou.call(this,a);
this.A={key:g.ki(),name:g.Q("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.Ol(64);this.H=0},Eua=function(a,b,c){a.F=c;
a.g.V("presentingplayerstatechange",new g.dz(c,b))},m$=function(a,b,c){if(b.key!=a.B.key)if(b.key==a.A.key)R9();
else{a.B=b;var d;if(!c){c=a.g.Le();d=a.g.getVideoData().videoId;var e;if(c){e=[];for(var f=0;f<c.getLength();f++)e[f]=c.Vb(f).videoId}else e=[a.g.getVideoData().videoId];d={videoIds:e,listId:a.g.getPlaylistId(),videoId:d,index:Math.max(a.g.xz(),0),currentTime:a.g.getCurrentTime()}}a=d;P9("Connecting to: "+g.xf(b));"cast-selector-receiver"==b.key?(y9(a||null),b=a||null,D9()?w9().setLaunchParams(b):F9("setLaunchParams called before ready.")):!a&&Q9()&&z9()==b.key?g.Ri("yt-remote-connection-change",
!0):(R9(),y9(a||null),a=B9().Kd(),(b=g.mi(a,b.key))&&N9(b,1))}};
g.C(u9,g.Hw);g.h=u9.prototype;g.h.Kd=function(a){return this.Sc.$_gs(a)};
g.h.contains=function(a){return!!this.Sc.$_c(a)};
g.h.get=function(a){return this.Sc.$_g(a)};
g.h.start=function(){this.Sc.$_st()};
g.h.vn=function(a,b,c){this.Sc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Sc.$_r(a,b,c)};
g.h.kn=function(a,b,c,d){this.Sc.$_un(a,b,c,d)};
g.h.R=function(){for(var a=0,b=this.o.length;a<b;++a)this.Sc.$_ubk(this.o[a]);this.o.length=0;this.Sc=null;u9.M.R.call(this)};
g.h.JN=function(){this.V("screenChange")};
g.h.lK=function(){this.V("onlineScreenChange")};
var A9=null,H9=[],J9=null,M9=null;g.C(T9,g.bl);g.h=T9.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.w,$9(this,"play")):V9(this,"play"),Y9(this,1,g.Qy(U9(this))),this.V("remotePlayerChange")):X9(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.w,$9(this,"pause")):V9(this,"pause"),Y9(this,2,g.Qy(U9(this))),this.V("remotePlayerChange")):X9(this,this.pause)};
g.h.kz=function(a){if(1==this.g){if(this.o){var b=U9(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.ob()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.w,$9(this,"seekTo",{newTime:a}))}else V9(this,"seekTo",{newTime:a});Y9(this,3,a);this.V("remotePlayerChange")}else X9(this,g.A(this.kz,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.w,$9(this,"stopVideo")):V9(this,"stopVideo");var a=U9(this);a.index=-1;a.videoId="";g.Oy(a);W9(this,a);this.V("remotePlayerChange")}else X9(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=U9(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.z)(function(){Z9("set receiver volume: "+d)},this),(0,g.z)(function(){this.Xb("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.z)(function(){Z9("set receiver muted: "+b)},this),(0,g.z)(function(){this.Xb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);V9(this,"setVolume",e)}c.muted=b;c.volume=a;W9(this,c)}else X9(this,g.A(this.setVolume,a,b))};
g.h.wy=function(a,b){if(1==this.g){var c=U9(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.xf(b.style),g.ac(d,c.o));V9(this,"setSubtitlesTrack",d);W9(this,c)}else X9(this,g.A(this.wy,a,b))};
g.h.ur=function(a,b){if(1==this.g){V9(this,"setAudioTrack",{videoId:a,audioTrackId:b.Ic.id});var c=U9(this);c.audioTrackId=b.Ic.id;W9(this,c)}else X9(this,g.A(this.ur,a,b))};
g.h.jz=function(a,b){if(1==this.g){if(a&&b){var c=U9(this);g.Ry(c,a,b);W9(this,c)}V9(this,"previous")}else X9(this,g.A(this.jz,a,b))};
g.h.iz=function(a,b){if(1==this.g){if(a&&b){var c=U9(this);g.Ry(c,a,b);W9(this,c)}V9(this,"next")}else X9(this,g.A(this.iz,a,b))};
g.h.fu=function(){1==this.g?V9(this,"dismissAutoplay"):X9(this,this.fu)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.V("proxyStateChange",a,this.g)}T9.M.dispose.call(this)};
g.h.R=function(){oua(this);this.B=null;this.C.clear();S9(this,null);T9.M.R.call(this)};
g.h.vr=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.Ly(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.FK=function(a,b){this.V(a,b)};
g.h.yI=function(a){if(!a)this.Uj(null),S9(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=U9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)Z9("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,W9(this,b)}};
g.h.Uj=function(a){Z9("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),pua(this),this.V("remotePlayerChange")};
g.h.xI=function(a){a?(pua(this),this.V("remotePlayerChange")):this.Uj(null)};
g.h.II=function(){var a=hua();a&&S9(this,a)};
g.h.Xb=function(a){g.Dw("CP",a)};
var j$=[];g.h=Bua.prototype;g.h.oh=function(a,b,c){var d=this.g;if(g.p(c)?c:this.o)d="https://"+this.A+this.B+this.g;return g.gg(d+a,b||{})};
g.h.tr=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Ib:g.A(this.EN,c,!0),onError:g.A(this.DN,d),cd:g.A(this.FN,d)};b&&(c.Ob=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Vi(a,c)};
g.h.EN=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.DN=function(a,b){a(Error("Request error: "+b.status))};
g.h.FN=function(a){a(Error("request timed out"))};
g.C(b$,g.J);g.h=b$.prototype;
g.h.R=function(){b$.M.R.call(this);this.o.stop();this.A.stop();this.J();this.aa.removeEventListener("onVolumeChange",this.Cm,this);this.aa.removeEventListener("onCaptionsTrackListChanged",this.Tw,this);this.aa.removeEventListener("captionschanged",this.Hw,this);this.aa.removeEventListener("videoplayerreset",this.Xj,this);this.aa.removeEventListener("captionssettingschanged",this.Oq,this);this.aa.removeEventListener("mdxautoplaycancel",this.xt,this);this.g.unsubscribe("proxyStateChange",this.ix,this);
this.g.unsubscribe("remotePlayerChange",this.Wj,this);this.g.unsubscribe("remoteQueueChange",this.Xj,this);this.g.unsubscribe("autoplayUpNext",this.Fw,this);this.g.unsubscribe("previousNextChange",this.fx,this);this.g.unsubscribe("nowAutoplaying",this.Ww,this);this.g.unsubscribe("autoplayDismissed",this.Ew,this);this.g=this.H=null};
g.h.eA=function(a,b){2==this.g.g||(e$(this)?this.vF.apply(this,arguments):this.rF.apply(this,arguments))};
g.h.Hw=function(a){this.eA("control_subtitles_set_track",g.Ub(a)?null:a)};
g.h.Oq=function(){var a=this.aa.Uc("captions","track");g.Ub(a)||g$(this,a)};
g.h.rF=function(a,b){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":h$(this,this.aa.getCurrentTime());break;case "control_seek":h$(this,c[0]);break;case "control_subtitles_set_track":g$(this,c[0]);break;case "control_set_audio_track":c=c[0],e$(this)&&this.g.ur(f$(this),c)}};
g.h.vF=function(a,b){if(1081!=U9(this.g).g||"control_seek"!=a){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":U9(this.g).ob()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.F.hi(c[0],c[1]);break;case "control_subtitles_set_track":g$(this,c[0]);break;case "control_set_audio_track":c=c[0],e$(this)&&this.g.ur(f$(this),c)}}};
g.h.Cm=function(a){if(e$(this)){this.g.unsubscribe("remotePlayerChange",this.Wj,this);var b=Math.round(a.volume);a=!!a.muted;var c=U9(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.G.start();this.g.subscribe("remotePlayerChange",this.Wj,this)}};
g.h.Tw=function(){g.Ub(this.B)||Dua(this,this.B);this.C=!1};
g.h.ix=function(a,b){this.A.stop();2==b&&this.Fy()};
g.h.Wj=function(){if(e$(this)){this.o.stop();var a=U9(this.g);switch(a.g){case 1081:d$(this,new g.Ol(8));break;case 1:this.Ey();d$(this,new g.Ol(8));break;case 1083:case 3:d$(this,new g.Ol(9));break;case 0:d$(this,new g.Ol(2));this.F.stop();c$(this,this.aa.getVideoData().lengthSeconds);break;case 1082:d$(this,new g.Ol(4));break;case 2:d$(this,new g.Ol(4));c$(this,g.Qy(a));break;case -1:d$(this,new g.Ol(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.Q("YTP_MDX_PLAYER_ERROR")},d$(this,
new g.Ol(128,a))}var a=U9(this.g).o,b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.B=a,Dua(this,a));a=U9(this.g);-1==a.volume||Math.round(this.aa.getVolume())==a.volume&&this.aa.Sd()==a.muted||this.G.isActive()||this.Vy()}else Cua(this)};
g.h.fx=function(){this.aa.V("mdxpreviousnextchange")};
g.h.Xj=function(){e$(this)||Cua(this)};
g.h.xt=function(){this.g.fu()};
g.h.Fw=function(a){a&&(a=g.Vi("/watch_queue_ajax",{method:"GET",Fc:{action_get_watch_queue_item:1,video_id:a},Ib:(0,g.z)(this.CL,this)}))&&(this.J=(0,g.z)(a.abort,a))};
g.h.CL=function(a,b){var c=new g.et({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.aa.V("mdxautoplayupnext",c)};
g.h.Ww=function(a){(0,window.isNaN)(a)||this.aa.V("mdxnowautoplaying",a)};
g.h.Ew=function(){this.aa.V("mdxautoplaycanceled")};
g.h.IP=function(a,b){-1==U9(this.g).g?h$(this,a):b&&this.g.kz(a)};
g.h.Vy=function(){if(e$(this)){var a=U9(this.g);this.aa.removeEventListener("onVolumeChange",this.Cm,this);a.muted?this.aa.mute():this.aa.gg();this.aa.setVolume(a.volume);this.aa.addEventListener("onVolumeChange",this.Cm,this)}};
g.h.Ey=function(){this.o.stop();if(!this.g.isDisposed()){var a=U9(this.g);a.ob()&&d$(this,new g.Ol(8));c$(this,g.Qy(a));this.o.start()}};
g.h.Fy=function(){this.A.stop();this.o.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.A.start()};
g.C(l$,g.ou);g.h=l$.prototype;g.h.create=function(){Gua("embedded"==g.V(this.g).g);this.D.push(g.Ni("yt-remote-before-disconnect",this.uI,this));this.D.push(g.Ni("yt-remote-connection-change",this.OK,this));this.D.push(g.Ni("yt-remote-receiver-availability-change",this.gx,this));this.D.push(g.Ni("yt-remote-auto-connect",this.MK,this));this.D.push(g.Ni("yt-remote-receiver-resumed",this.LK,this));this.gx()};
g.h.load=function(){this.g.qo();l$.M.load.call(this);this.C=new b$(this,this.g,this.o);var a;a=(a=fua())?a.currentTime:0;var b=Q9()?new T9(x9(),void 0):null;0==a&&b&&(a=g.Qy(U9(b)));0!=a&&(this.H=a||0,this.g.V("progresssync",a,void 0));Eua(this,this.F,this.F);g.o2(this.g.app,6)};
g.h.unload=function(){this.g.V("mdxautoplaycanceled");this.B=this.A;g.Gb(this.C,this.o);this.o=this.C=null;l$.M.unload.call(this);g.o2(this.g.app,5)};
g.h.R=function(){g.Oi(this.D);l$.M.R.call(this)};
g.h.Gk=function(a,b){this.loaded&&this.C.eA.apply(this.C,arguments)};
g.h.YE=function(){return this.loaded?this.C.suggestion:null};
g.h.gf=function(){return this.o?U9(this.o).gf:!1};
g.h.hasNext=function(){return this.o?U9(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.nP=function(){var a=U9(this.o),b=this.g.getVideoData(),c=this.g.wh(),d=b.clipEnd,b=b.clipStart,e=this.getCurrentTime(),f=a.getDuration(),k;k=a.H?a.B+((0,g.G)()-a.A)/1E3:a.B;var l=1>=Wta(a)-this.getCurrentTime(),m=a.J,n=Wta(a),a=0<a.C?a.C+((0,g.G)()-a.A)/1E3:a.C;return{allowSeeking:c,clipEnd:d,clipStart:b,current:e,displayedStart:-1,duration:f,ingestionTime:k,isPeggedToLive:l,loaded:m,seekableEnd:n,seekableStart:a}};
g.h.oP=function(){this.o&&this.o.iz()};
g.h.pP=function(){this.o&&this.o.jz()};
g.h.uI=function(a){1==a&&(this.J=this.o?U9(this.o):null)};
g.h.OK=function(){var a=Q9()?new T9(x9(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Fb(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.getVideoData().videoId&&this.g.Nc(g.Qy(a)));this.g.V("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.gx=function(){this.G=[this.A].concat(Fua());var a=i$()||this.A;m$(this,a,!this.loaded);this.g.wa("onMdxReceiversChange")};
g.h.MK=function(){var a=i$();m$(this,a)};
g.h.LK=function(){this.B=i$()};
g.h.mP=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?k$():m$(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&k$(),!0):!1}};
g.h.qP=function(){V9(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.he=function(){return!1};
window._exportCheck==g.Ba&&g.oa("ytmod.player.remote",l$,void 0);})(_yt_player);
